# -- Main Menu --

[[main]]
  identifier = "student-body"
  name = "Student Body"
  pageRef = "student-body"
  weight = 10

[[main]]
  identifier = "student-body-about"
  name = "About us"
  parent = "student-body"
  pageRef = "student-body/about"
  weight = 11

[[main]]
  identifier = "student-body-events"
  name = "Events"
  parent = "student-body"
  pageRef = "student-body/events"
  weight = 12

[[main]]
  identifier = "student-body-projects"
  name = "Projects"
  parent = "student-body"
  pageRef = "student-body/projects"
  weight = 13


[[main]]
  identifier = "professional-body"
  name = "Professional Body"
  pageRef = "professional-body"
  weight = 20

[[main]]
  identifier = "professional-body-about"
  name = "About us"
  parent = "professional-body"
  pageRef = "professional-body/about"
  weight = 21

[[main]]
  identifier = "professional-body-events"
  name = "Events"
  parent = "professional-body"
  pageRef = "professional-body/events"
  weight = 22

[[main]]
  identifier = "professional-body-projects"
  name = "Projects"
  parent = "professional-body"
  pageRef = "professional-body/projects"
  weight = 23


# -- Footer Menu --

[[footer]]
  identifier = "meeting-notes"
  name = "Meeting Notes"
  pageRef = "meeting-notes"
  weight = 10

[[footer]]
  identifier = "contact-us"
  name = "Contact Us"
  url = "mailto:scicommsocimperial@gmail.com"
  weight = 20